
# Utilisez une image Java JRE comme base
FROM eclipse-temurin:17-jdk-alpine

# Copiez les fichiers .class (compiled Java) dans le conteneur
COPY Main.class .

# Exécutez l'application Java en utilisant la commande "java Main"
CMD ["java", "Main"]




